# Generated by Django 5.2.6 on 2025-09-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimage_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
