# Generated by Django 5.2.6 on 2026-02-16 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentRequest',
        ),
    ]
